{
    "beer": [
        {
            "category": "Light Lager",
            "name": "Lite American Lager",
            "id": "1A",
            "OG_min": 1.03,
            "OG_max": 1.04,
            "FG_min": 0.998,
            "FG_max": 1.008,
            "IBU_min": 8.0,
            "IBU_max": 12.0,
            "SRM_min": 2.0,
            "SRM_max": 3.0,
            "ABV_min": 3.2,
            "ABV_max": 4.2
        },
        {
            "category": "Light Lager",
            "name": "Standard American Lager",
            "id": "1B",
            "OG_min": 1.04,
            "OG_max": 1.05,
            "FG_min": 1.004,
            "FG_max": 1.01,
            "IBU_min": 8.0,
            "IBU_max": 15.0,
            "SRM_min": 2.0,
            "SRM_max": 4.0,
            "ABV_min": 4.2,
            "ABV_max": 5.1
        },
        {
            "category": "Light Lager",
            "name": "Premium American Lager",
            "id": "1C",
            "OG_min": 1.046,
            "OG_max": 1.056,
            "FG_min": 1.008,
            "FG_max": 1.012,
            "IBU_min": 15.0,
            "IBU_max": 25.0,
            "SRM_min": 2.0,
            "SRM_max": 6.0,
            "ABV_min": 4.7,
            "ABV_max": 6.0
        },
        {
            "category": "Light Lager",
            "name": "Munich Helles",
            "id": "1D",
            "OG_min": 1.045,
            "OG_max": 1.051,
            "FG_min": 1.008,
            "FG_max": 1.012,
            "IBU_min": 16.0,
            "IBU_max": 22.0,
            "SRM_min": 3.0,
            "SRM_max": 5.0,
            "ABV_min": 4.7,
            "ABV_max": 5.4
        },
        {
            "category": "Light Lager",
            "name": "Dortmunder Export",
            "id": "1E",
            "OG_min": 1.048,
            "OG_max": 1.056,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 23.0,
            "IBU_max": 30.0,
            "SRM_min": 4.0,
            "SRM_max": 6.0,
            "ABV_min": 4.8,
            "ABV_max": 6.0
        },
        {
            "category": "Pilsner",
            "name": "German Pilsner (Pils)",
            "id": "2A",
            "OG_min": 1.044,
            "OG_max": 1.05,
            "FG_min": 1.008,
            "FG_max": 1.013,
            "IBU_min": 25.0,
            "IBU_max": 45.0,
            "SRM_min": 2.0,
            "SRM_max": 5.0,
            "ABV_min": 4.4,
            "ABV_max": 5.2
        },
        {
            "category": "Pilsner",
            "name": "Bohemian Pilsener",
            "id": "2B",
            "OG_min": 1.044,
            "OG_max": 1.056,
            "FG_min": 1.013,
            "FG_max": 1.017,
            "IBU_min": 35.0,
            "IBU_max": 45.0,
            "SRM_min": 3.5,
            "SRM_max": 6.0,
            "ABV_min": 4.2,
            "ABV_max": 5.4
        },
        {
            "category": "Pilsner",
            "name": "Classic American Pilsner",
            "id": "2C",
            "OG_min": 1.044,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 3.0,
            "SRM_max": 6.0,
            "ABV_min": 4.5,
            "ABV_max": 6.0
        },
        {
            "category": "European Amber Lager",
            "name": "Vienna Lager",
            "id": "3A",
            "OG_min": 1.046,
            "OG_max": 1.052,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 18.0,
            "IBU_max": 30.0,
            "SRM_min": 10.0,
            "SRM_max": 16.0,
            "ABV_min": 4.5,
            "ABV_max": 5.7
        },
        {
            "category": "European Amber Lager",
            "name": "Oktoberfest/M\u00e4rzen",
            "id": "3B",
            "OG_min": 1.05,
            "OG_max": 1.056,
            "FG_min": 1.012,
            "FG_max": 1.016,
            "IBU_min": 20.0,
            "IBU_max": 28.0,
            "SRM_min": 7.0,
            "SRM_max": 14.0,
            "ABV_min": 4.8,
            "ABV_max": 5.7
        },
        {
            "category": "Dark Lager",
            "name": "Dark American Lager",
            "id": "4A",
            "OG_min": 1.044,
            "OG_max": 1.056,
            "FG_min": 1.008,
            "FG_max": 1.012,
            "IBU_min": 8.0,
            "IBU_max": 20.0,
            "SRM_min": 14.0,
            "SRM_max": 22.0,
            "ABV_min": 4.2,
            "ABV_max": 6.0
        },
        {
            "category": "Dark Lager",
            "name": "Munich Dunkel",
            "id": "4B",
            "OG_min": 1.048,
            "OG_max": 1.056,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 18.0,
            "IBU_max": 28.0,
            "SRM_min": 14.0,
            "SRM_max": 28.0,
            "ABV_min": 4.5,
            "ABV_max": 5.6
        },
        {
            "category": "Dark Lager",
            "name": "Schwarzbier (Black Beer)",
            "id": "4C",
            "OG_min": 1.046,
            "OG_max": 1.052,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 22.0,
            "IBU_max": 32.0,
            "SRM_min": 17.0,
            "SRM_max": 30.0,
            "ABV_min": 4.4,
            "ABV_max": 5.4
        },
        {
            "category": "Bock",
            "name": "Maibock/Helles Bock",
            "id": "5A",
            "OG_min": 1.064,
            "OG_max": 1.072,
            "FG_min": 1.011,
            "FG_max": 1.018,
            "IBU_min": 23.0,
            "IBU_max": 35.0,
            "SRM_min": 6.0,
            "SRM_max": 11.0,
            "ABV_min": 6.3,
            "ABV_max": 7.4
        },
        {
            "category": "Bock",
            "name": "Traditional Bock",
            "id": "5B",
            "OG_min": 1.064,
            "OG_max": 1.072,
            "FG_min": 1.013,
            "FG_max": 1.019,
            "IBU_min": 20.0,
            "IBU_max": 27.0,
            "SRM_min": 14.0,
            "SRM_max": 22.0,
            "ABV_min": 6.3,
            "ABV_max": 7.2
        },
        {
            "category": "Bock",
            "name": "Doppelbock",
            "id": "5C",
            "OG_min": 1.072,
            "OG_max": 1.096,
            "FG_min": 1.016,
            "FG_max": 1.024,
            "IBU_min": 16.0,
            "IBU_max": 26.0,
            "SRM_min": 6.0,
            "SRM_max": 25.0,
            "ABV_min": 7.0,
            "ABV_max": 10.0
        },
        {
            "category": "Bock",
            "name": "Eisbock",
            "id": "5D",
            "OG_min": 1.078,
            "OG_max": 1.12,
            "FG_min": 1.02,
            "FG_max": 1.035,
            "IBU_min": 25.0,
            "IBU_max": 35.0,
            "SRM_min": 18.0,
            "SRM_max": 30.0,
            "ABV_min": 9.0,
            "ABV_max": 14.0
        },
        {
            "category": "Light Hybrid Beer",
            "name": "Cream Ale",
            "id": "6A",
            "OG_min": 1.042,
            "OG_max": 1.055,
            "FG_min": 1.006,
            "FG_max": 1.012,
            "IBU_min": 15.0,
            "IBU_max": 20.0,
            "SRM_min": 2.5,
            "SRM_max": 5.0,
            "ABV_min": 4.2,
            "ABV_max": 5.6
        },
        {
            "category": "Light Hybrid Beer",
            "name": "Blonde Ale",
            "id": "6B",
            "OG_min": 1.038,
            "OG_max": 1.054,
            "FG_min": 1.008,
            "FG_max": 1.013,
            "IBU_min": 15.0,
            "IBU_max": 28.0,
            "SRM_min": 3.0,
            "SRM_max": 6.0,
            "ABV_min": 3.8,
            "ABV_max": 5.5
        },
        {
            "category": "Light Hybrid Beer",
            "name": "K\u00f6lsch",
            "id": "6C",
            "OG_min": 1.044,
            "OG_max": 1.05,
            "FG_min": 1.007,
            "FG_max": 1.011,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 3.5,
            "SRM_max": 5.0,
            "ABV_min": 4.4,
            "ABV_max": 5.2
        },
        {
            "category": "Light Hybrid Beer",
            "name": "American Wheat or Rye Beer",
            "id": "6D",
            "OG_min": 1.04,
            "OG_max": 1.055,
            "FG_min": 1.008,
            "FG_max": 1.013,
            "IBU_min": 15.0,
            "IBU_max": 30.0,
            "SRM_min": 3.0,
            "SRM_max": 6.0,
            "ABV_min": 4.0,
            "ABV_max": 5.5
        },
        {
            "category": "Amber Hybrid Beer",
            "name": "Northern German Altbier",
            "id": "7A",
            "OG_min": 1.046,
            "OG_max": 1.054,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 13.0,
            "SRM_max": 19.0,
            "ABV_min": 4.5,
            "ABV_max": 5.2
        },
        {
            "category": "Amber Hybrid Beer",
            "name": "California Common Beer",
            "id": "7B",
            "OG_min": 1.048,
            "OG_max": 1.054,
            "FG_min": 1.011,
            "FG_max": 1.014,
            "IBU_min": 30.0,
            "IBU_max": 45.0,
            "SRM_min": 10.0,
            "SRM_max": 14.0,
            "ABV_min": 4.5,
            "ABV_max": 5.5
        },
        {
            "category": "Amber Hybrid Beer",
            "name": "D\u00fcsseldorf Altbier",
            "id": "7C",
            "OG_min": 1.046,
            "OG_max": 1.054,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 35.0,
            "IBU_max": 50.0,
            "SRM_min": 13.0,
            "SRM_max": 17.0,
            "ABV_min": 4.5,
            "ABV_max": 5.2
        },
        {
            "category": "English Pale Ale",
            "name": "Standard/Ordinary Bitter",
            "id": "8A",
            "OG_min": 1.032,
            "OG_max": 1.04,
            "FG_min": 1.007,
            "FG_max": 1.011,
            "IBU_min": 25.0,
            "IBU_max": 35.0,
            "SRM_min": 4.0,
            "SRM_max": 14.0,
            "ABV_min": 3.2,
            "ABV_max": 3.8
        },
        {
            "category": "English Pale Ale",
            "name": "Special/Best/Premium Bitter",
            "id": "8B",
            "OG_min": 1.04,
            "OG_max": 1.048,
            "FG_min": 1.008,
            "FG_max": 1.012,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 5.0,
            "SRM_max": 16.0,
            "ABV_min": 3.8,
            "ABV_max": 4.6
        },
        {
            "category": "English Pale Ale",
            "name": "Extra Special/Strong Bitter (English Pale Ale)",
            "id": "8C",
            "OG_min": 1.048,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 30.0,
            "IBU_max": 50.0,
            "SRM_min": 6.0,
            "SRM_max": 18.0,
            "ABV_min": 4.6,
            "ABV_max": 6.2
        },
        {
            "category": "Scottish and Irish Ale",
            "name": "Scottish Light 60/-",
            "id": "9A",
            "OG_min": 1.03,
            "OG_max": 1.035,
            "FG_min": 1.01,
            "FG_max": 1.013,
            "IBU_min": 10.0,
            "IBU_max": 20.0,
            "SRM_min": 9.0,
            "SRM_max": 17.0,
            "ABV_min": 2.5,
            "ABV_max": 3.2
        },
        {
            "category": "Scottish and Irish Ale",
            "name": "Scottish Heavy 70/-",
            "id": "9B",
            "OG_min": 1.035,
            "OG_max": 1.04,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 10.0,
            "IBU_max": 25.0,
            "SRM_min": 9.0,
            "SRM_max": 17.0,
            "ABV_min": 3.2,
            "ABV_max": 3.9
        },
        {
            "category": "Scottish and Irish Ale",
            "name": "Scottish Export 80/-",
            "id": "9C",
            "OG_min": 1.04,
            "OG_max": 1.054,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 15.0,
            "IBU_max": 30.0,
            "SRM_min": 9.0,
            "SRM_max": 17.0,
            "ABV_min": 3.9,
            "ABV_max": 5.0
        },
        {
            "category": "Scottish and Irish Ale",
            "name": "Irish Red Ale",
            "id": "9D",
            "OG_min": 1.044,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 17.0,
            "IBU_max": 28.0,
            "SRM_min": 9.0,
            "SRM_max": 18.0,
            "ABV_min": 4.0,
            "ABV_max": 6.0
        },
        {
            "category": "Scottish and Irish Ale",
            "name": "Strong Scotch Ale",
            "id": "9E",
            "OG_min": 1.07,
            "OG_max": 1.13,
            "FG_min": 1.018,
            "FG_max": 1.03,
            "IBU_min": 17.0,
            "IBU_max": 35.0,
            "SRM_min": 14.0,
            "SRM_max": 25.0,
            "ABV_min": 6.5,
            "ABV_max": 10.0
        },
        {
            "category": "American Ale",
            "name": "American Pale Ale",
            "id": "10A",
            "OG_min": 1.045,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 30.0,
            "IBU_max": 45.0,
            "SRM_min": 5.0,
            "SRM_max": 14.0,
            "ABV_min": 4.5,
            "ABV_max": 6.0
        },
        {
            "category": "American Ale",
            "name": "American Amber Ale",
            "id": "10B",
            "OG_min": 1.045,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.015,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 10.0,
            "SRM_max": 17.0,
            "ABV_min": 4.5,
            "ABV_max": 6.0
        },
        {
            "category": "American Ale",
            "name": "American Brown Ale",
            "id": "10C",
            "OG_min": 1.045,
            "OG_max": 1.06,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 20.0,
            "IBU_max": 40.0,
            "SRM_min": 18.0,
            "SRM_max": 35.0,
            "ABV_min": 4.3,
            "ABV_max": 6.2
        },
        {
            "category": "English Brown Ale",
            "name": "Mild",
            "id": "11A",
            "OG_min": 1.03,
            "OG_max": 1.038,
            "FG_min": 1.008,
            "FG_max": 1.013,
            "IBU_min": 10.0,
            "IBU_max": 25.0,
            "SRM_min": 12.0,
            "SRM_max": 25.0,
            "ABV_min": 2.8,
            "ABV_max": 4.5
        },
        {
            "category": "English Brown Ale",
            "name": "Southern English Brown",
            "id": "11B",
            "OG_min": 1.035,
            "OG_max": 1.042,
            "FG_min": 1.011,
            "FG_max": 1.014,
            "IBU_min": 12.0,
            "IBU_max": 20.0,
            "SRM_min": 19.0,
            "SRM_max": 35.0,
            "ABV_min": 2.8,
            "ABV_max": 4.2
        },
        {
            "category": "English Brown Ale",
            "name": "Northern English Brown Ale",
            "id": "11C",
            "OG_min": 1.04,
            "OG_max": 1.052,
            "FG_min": 1.008,
            "FG_max": 1.013,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 12.0,
            "SRM_max": 22.0,
            "ABV_min": 4.2,
            "ABV_max": 5.4
        },
        {
            "category": "Porter",
            "name": "Brown Porter",
            "id": "12A",
            "OG_min": 1.04,
            "OG_max": 1.052,
            "FG_min": 1.008,
            "FG_max": 1.014,
            "IBU_min": 18.0,
            "IBU_max": 35.0,
            "SRM_min": 20.0,
            "SRM_max": 30.0,
            "ABV_min": 4.0,
            "ABV_max": 5.4
        },
        {
            "category": "Porter",
            "name": "Robust Porter",
            "id": "12B",
            "OG_min": 1.048,
            "OG_max": 1.065,
            "FG_min": 1.012,
            "FG_max": 1.016,
            "IBU_min": 25.0,
            "IBU_max": 50.0,
            "SRM_min": 22.0,
            "SRM_max": 35.0,
            "ABV_min": 4.8,
            "ABV_max": 6.0
        },
        {
            "category": "Porter",
            "name": "Baltic Porter",
            "id": "12C",
            "OG_min": 1.06,
            "OG_max": 1.09,
            "FG_min": 1.016,
            "FG_max": 1.024,
            "IBU_min": 20.0,
            "IBU_max": 40.0,
            "SRM_min": 17.0,
            "SRM_max": 30.0,
            "ABV_min": 5.5,
            "ABV_max": 9.5
        },
        {
            "category": "Stout",
            "name": "Dry Stout",
            "id": "13A",
            "OG_min": 1.036,
            "OG_max": 1.05,
            "FG_min": 1.007,
            "FG_max": 1.011,
            "IBU_min": 30.0,
            "IBU_max": 45.0,
            "SRM_min": 25.0,
            "SRM_max": 40.0,
            "ABV_min": 4.0,
            "ABV_max": 5.0
        },
        {
            "category": "Stout",
            "name": "Sweet Stout",
            "id": "13B",
            "OG_min": 1.042,
            "OG_max": 1.056,
            "FG_min": 1.01,
            "FG_max": 1.023,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 30.0,
            "SRM_max": 40.0,
            "ABV_min": 4.0,
            "ABV_max": 6.0
        },
        {
            "category": "Stout",
            "name": "Oatmeal Stout",
            "id": "13C",
            "OG_min": 1.048,
            "OG_max": 1.065,
            "FG_min": 1.01,
            "FG_max": 1.018,
            "IBU_min": 25.0,
            "IBU_max": 40.0,
            "SRM_min": 22.0,
            "SRM_max": 40.0,
            "ABV_min": 4.2,
            "ABV_max": 5.9
        },
        {
            "category": "Stout",
            "name": "Foreign Extra Stout",
            "id": "13D",
            "OG_min": 1.056,
            "OG_max": 1.075,
            "FG_min": 1.01,
            "FG_max": 1.018,
            "IBU_min": 30.0,
            "IBU_max": 70.0,
            "SRM_min": 30.0,
            "SRM_max": 40.0,
            "ABV_min": 5.5,
            "ABV_max": 8.0
        },
        {
            "category": "Stout",
            "name": "American Stout",
            "id": "13E",
            "OG_min": 1.05,
            "OG_max": 1.075,
            "FG_min": 1.01,
            "FG_max": 1.022,
            "IBU_min": 35.0,
            "IBU_max": 75.0,
            "SRM_min": 30.0,
            "SRM_max": 40.0,
            "ABV_min": 5.0,
            "ABV_max": 7.0
        },
        {
            "category": "Stout",
            "name": "Russian Imperial Stout",
            "id": "13F",
            "OG_min": 1.075,
            "OG_max": 1.095,
            "FG_min": 1.018,
            "FG_max": 1.03,
            "IBU_min": 50.0,
            "IBU_max": 90.0,
            "SRM_min": 30.0,
            "SRM_max": 40.0,
            "ABV_min": 8.0,
            "ABV_max": 12.0
        },
        {
            "category": "India Pale Ale (IPA)",
            "name": "English IPA",
            "id": "14A",
            "OG_min": 1.05,
            "OG_max": 1.075,
            "FG_min": 1.01,
            "FG_max": 1.018,
            "IBU_min": 40.0,
            "IBU_max": 60.0,
            "SRM_min": 8.0,
            "SRM_max": 14.0,
            "ABV_min": 5.0,
            "ABV_max": 7.5
        },
        {
            "category": "India Pale Ale (IPA)",
            "name": "American IPA",
            "id": "14B",
            "OG_min": 1.056,
            "OG_max": 1.075,
            "FG_min": 1.01,
            "FG_max": 1.018,
            "IBU_min": 40.0,
            "IBU_max": 60.0,
            "SRM_min": 6.0,
            "SRM_max": 15.0,
            "ABV_min": 5.5,
            "ABV_max": 7.5
        },
        {
            "category": "India Pale Ale (IPA)",
            "name": "Imperial IPA",
            "id": "14C",
            "OG_min": 1.075,
            "OG_max": 1.09,
            "FG_min": 1.012,
            "FG_max": 1.02,
            "IBU_min": 60.0,
            "IBU_max": 100.0,
            "SRM_min": 8.0,
            "SRM_max": 15.0,
            "ABV_min": 7.5,
            "ABV_max": 10.0
        },
        {
            "category": "German Wheat and Rye Beer",
            "name": "Weizen/Weissbier",
            "id": "15A",
            "OG_min": 1.044,
            "OG_max": 1.052,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 8.0,
            "IBU_max": 15.0,
            "SRM_min": 2.0,
            "SRM_max": 8.0,
            "ABV_min": 4.3,
            "ABV_max": 5.6
        },
        {
            "category": "German Wheat and Rye Beer",
            "name": "Dunkelweizen",
            "id": "15B",
            "OG_min": 1.044,
            "OG_max": 1.056,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 10.0,
            "IBU_max": 18.0,
            "SRM_min": 14.0,
            "SRM_max": 23.0,
            "ABV_min": 4.3,
            "ABV_max": 5.6
        },
        {
            "category": "German Wheat and Rye Beer",
            "name": "Weizenbock",
            "id": "15C",
            "OG_min": 1.064,
            "OG_max": 1.08,
            "FG_min": 1.015,
            "FG_max": 1.022,
            "IBU_min": 15.0,
            "IBU_max": 30.0,
            "SRM_min": 12.0,
            "SRM_max": 25.0,
            "ABV_min": 6.5,
            "ABV_max": 8.0
        },
        {
            "category": "German Wheat and Rye Beer",
            "name": "Roggenbier (German Rye Beer)",
            "id": "15D",
            "OG_min": 1.046,
            "OG_max": 1.056,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 10.0,
            "IBU_max": 20.0,
            "SRM_min": 14.0,
            "SRM_max": 19.0,
            "ABV_min": 4.5,
            "ABV_max": 6.0
        },
        {
            "category": "Belgian and French Ale",
            "name": "Witbier",
            "id": "16A",
            "OG_min": 1.044,
            "OG_max": 1.052,
            "FG_min": 1.008,
            "FG_max": 1.012,
            "IBU_min": 10.0,
            "IBU_max": 20.0,
            "SRM_min": 2.0,
            "SRM_max": 4.0,
            "ABV_min": 4.5,
            "ABV_max": 5.5
        },
        {
            "category": "Belgian and French Ale",
            "name": "Belgian Pale Ale",
            "id": "16B",
            "OG_min": 1.048,
            "OG_max": 1.054,
            "FG_min": 1.01,
            "FG_max": 1.014,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 8.0,
            "SRM_max": 14.0,
            "ABV_min": 4.8,
            "ABV_max": 5.5
        },
        {
            "category": "Belgian and French Ale",
            "name": "Saison",
            "id": "16C",
            "OG_min": 1.048,
            "OG_max": 1.08,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 25.0,
            "IBU_max": 45.0,
            "SRM_min": 5.0,
            "SRM_max": 12.0,
            "ABV_min": 5.0,
            "ABV_max": 8.5
        },
        {
            "category": "Belgian and French Ale",
            "name": "Bi\u00e8re de Garde",
            "id": "16D",
            "OG_min": 1.06,
            "OG_max": 1.08,
            "FG_min": 1.012,
            "FG_max": 1.018,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 6.0,
            "SRM_max": 19.0,
            "ABV_min": 6.0,
            "ABV_max": 8.0
        },
        {
            "category": "Belgian and French Ale",
            "name": "Belgian Specialty Ale",
            "id": "16E",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Sour Ale",
            "name": "Berliner Weisse",
            "id": "17A",
            "OG_min": 1.028,
            "OG_max": 1.032,
            "FG_min": 1.004,
            "FG_max": 1.006,
            "IBU_min": 3.0,
            "IBU_max": 8.0,
            "SRM_min": 2.0,
            "SRM_max": 3.0,
            "ABV_min": 2.8,
            "ABV_max": 3.6
        },
        {
            "category": "Sour Ale",
            "name": "Flanders Red Ale",
            "id": "17B",
            "OG_min": 1.046,
            "OG_max": 1.054,
            "FG_min": 1.008,
            "FG_max": 1.016,
            "IBU_min": 15.0,
            "IBU_max": 25.0,
            "SRM_min": 10.0,
            "SRM_max": 16.0,
            "ABV_min": 5.0,
            "ABV_max": 5.5
        },
        {
            "category": "Sour Ale",
            "name": "Flanders Brown Ale/Oud Bruin",
            "id": "17C",
            "OG_min": 1.043,
            "OG_max": 1.077,
            "FG_min": 1.012,
            "FG_max": 1.016,
            "IBU_min": 15.0,
            "IBU_max": 25.0,
            "SRM_min": 15.0,
            "SRM_max": 20.0,
            "ABV_min": 4.0,
            "ABV_max": 8.0
        },
        {
            "category": "Sour Ale",
            "name": "Straight (Unblended) Lambic",
            "id": "17D",
            "OG_min": 1.04,
            "OG_max": 1.054,
            "FG_min": 1.0,
            "FG_max": 1.01,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 3.0,
            "SRM_max": 7.0,
            "ABV_min": 5.0,
            "ABV_max": 6.5
        },
        {
            "category": "Sour Ale",
            "name": "Gueuze",
            "id": "17E",
            "OG_min": 1.04,
            "OG_max": 1.06,
            "FG_min": 1.0,
            "FG_max": 1.006,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 3.0,
            "SRM_max": 7.0,
            "ABV_min": 5.0,
            "ABV_max": 8.0
        },
        {
            "category": "Sour Ale",
            "name": "Fruit Lambic",
            "id": "17F",
            "OG_min": 1.04,
            "OG_max": 1.06,
            "FG_min": 1.0,
            "FG_max": 1.01,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 3.0,
            "SRM_max": 7.0,
            "ABV_min": 5.0,
            "ABV_max": 7.0
        },
        {
            "category": "Belgian Strong Ale",
            "name": "Belgian Blond Ale",
            "id": "18A",
            "OG_min": 1.062,
            "OG_max": 1.075,
            "FG_min": 1.008,
            "FG_max": 1.016,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 4.0,
            "SRM_max": 6.0,
            "ABV_min": 6.0,
            "ABV_max": 7.5
        },
        {
            "category": "Belgian Strong Ale",
            "name": "Belgian Dubbel",
            "id": "18B",
            "OG_min": 1.062,
            "OG_max": 1.075,
            "FG_min": 1.01,
            "FG_max": 1.018,
            "IBU_min": 15.0,
            "IBU_max": 25.0,
            "SRM_min": 10.0,
            "SRM_max": 14.0,
            "ABV_min": 6.0,
            "ABV_max": 7.5
        },
        {
            "category": "Belgian Strong Ale",
            "name": "Belgian Tripel",
            "id": "18C",
            "OG_min": 1.075,
            "OG_max": 1.085,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 25.0,
            "IBU_max": 38.0,
            "SRM_min": 4.5,
            "SRM_max": 6.0,
            "ABV_min": 7.5,
            "ABV_max": 9.0
        },
        {
            "category": "Belgian Strong Ale",
            "name": "Belgian Golden Strong Ale",
            "id": "18D",
            "OG_min": 1.07,
            "OG_max": 1.095,
            "FG_min": 1.01,
            "FG_max": 1.016,
            "IBU_min": 25.0,
            "IBU_max": 35.0,
            "SRM_min": 4.0,
            "SRM_max": 6.0,
            "ABV_min": 7.5,
            "ABV_max": 10.0
        },
        {
            "category": "Belgian Strong Ale",
            "name": "Belgian Dark Strong Ale",
            "id": "18E",
            "OG_min": 1.075,
            "OG_max": 1.11,
            "FG_min": 1.01,
            "FG_max": 1.024,
            "IBU_min": 15.0,
            "IBU_max": 25.0,
            "SRM_min": 15.0,
            "SRM_max": 20.0,
            "ABV_min": 8.0,
            "ABV_max": 12.0
        },
        {
            "category": "Strong Ale",
            "name": "Old Ale",
            "id": "19A",
            "OG_min": 1.06,
            "OG_max": 1.09,
            "FG_min": 1.015,
            "FG_max": 1.022,
            "IBU_min": 30.0,
            "IBU_max": 60.0,
            "SRM_min": 10.0,
            "SRM_max": 22.0,
            "ABV_min": 6.0,
            "ABV_max": 9.0
        },
        {
            "category": "Strong Ale",
            "name": "English Barleywine",
            "id": "19B",
            "OG_min": 1.08,
            "OG_max": 1.12,
            "FG_min": 1.018,
            "FG_max": 1.03,
            "IBU_min": 35.0,
            "IBU_max": 70.0,
            "SRM_min": 8.0,
            "SRM_max": 22.0,
            "ABV_min": 8.0,
            "ABV_max": 12.0
        },
        {
            "category": "Strong Ale",
            "name": "American Barleywine",
            "id": "19C",
            "OG_min": 1.08,
            "OG_max": 1.12,
            "FG_min": 1.016,
            "FG_max": 1.03,
            "IBU_min": 50.0,
            "IBU_max": 120.0,
            "SRM_min": 10.0,
            "SRM_max": 19.0,
            "ABV_min": 8.0,
            "ABV_max": 12.0
        },
        {
            "category": "Fruit Beer",
            "name": "Fruit Beer",
            "id": "20A",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Spice/Herb/Vegetable Beer",
            "name": "Spice, Herb, or Vegetable Beer",
            "id": "21A",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Spice/Herb/Vegetable Beer",
            "name": "Christmas/Winter Specialty Spiced Beer",
            "id": "21B",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Smoke-Flavored and Wood-Aged Beer",
            "name": "Classic Rauchbier",
            "id": "22A",
            "OG_min": 1.05,
            "OG_max": 1.056,
            "FG_min": 1.012,
            "FG_max": 1.016,
            "IBU_min": 20.0,
            "IBU_max": 30.0,
            "SRM_min": 14.0,
            "SRM_max": 22.0,
            "ABV_min": 4.8,
            "ABV_max": 6.0
        },
        {
            "category": "Smoke-Flavored and Wood-Aged Beer",
            "name": "Other Smoked Beer",
            "id": "22B",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Smoke-Flavored and Wood-Aged Beer",
            "name": "Wood-Aged Beer",
            "id": "22C",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Specialty Beer",
            "name": "Specialty Beer",
            "id": "23A",
            "OG_min": 9999.0,
            "OG_max": 9999.0,
            "FG_min": 9999.0,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9999.0,
            "ABV_max": 9999.0
        },
        {
            "category": "Standard Cider and Perry",
            "name": "Common Cider",
            "id": "27A",
            "OG_min": 1.045,
            "OG_max": 1.065,
            "FG_min": 1.02,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 5.0,
            "ABV_min": 8.0,
            "ABV_max": 1.05
        },
        {
            "category": "Standard Cider and Perry",
            "name": "English Cider",
            "id": "27B",
            "OG_min": 1.075,
            "OG_max": 0.995,
            "FG_min": 1.01,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 6.0,
            "ABV_min": 9.0,
            "ABV_max": 1.05
        },
        {
            "category": "Standard Cider and Perry",
            "name": "French Cider",
            "id": "27C",
            "OG_min": 1.065,
            "OG_max": 1.01,
            "FG_min": 1.02,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 3.0,
            "ABV_min": 6.0,
            "ABV_max": 1.05
        },
        {
            "category": "Standard Cider and Perry",
            "name": "Common Perry",
            "id": "27D",
            "OG_min": 1.06,
            "OG_max": 1.0,
            "FG_min": 1.02,
            "FG_max": 9999.0,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 5.0,
            "ABV_min": 7.0,
            "ABV_max": 1.05
        },
        {
            "category": "Specialty Cider and Perry",
            "name": "New England Cider",
            "id": "28A",
            "OG_min": 1.06,
            "OG_max": 1.1,
            "FG_min": 0.995,
            "FG_max": 1.01,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 7.0,
            "ABV_max": 13.0
        },
        {
            "category": "Specialty Cider and Perry",
            "name": "Fruit Cider",
            "id": "28B",
            "OG_min": 1.045,
            "OG_max": 1.07,
            "FG_min": 0.995,
            "FG_max": 1.01,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 5.0,
            "ABV_max": 9.0
        },
        {
            "category": "Specialty Cider and Perry",
            "name": "Applewine",
            "id": "28C",
            "OG_min": 1.07,
            "OG_max": 1.1,
            "FG_min": 0.995,
            "FG_max": 1.01,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 9.0,
            "ABV_max": 12.0
        },
        {
            "category": "Specialty Cider and Perry",
            "name": "Other Specialty Cider/Perry",
            "id": "28D",
            "OG_min": 1.045,
            "OG_max": 1.1,
            "FG_min": 0.995,
            "FG_max": 1.02,
            "IBU_min": 9999.0,
            "IBU_max": 9999.0,
            "SRM_min": 9999.0,
            "SRM_max": 9999.0,
            "ABV_min": 5.0,
            "ABV_max": 12.0
        }
    ]
}
